# Generated by Django 4.2.16 on 2024-10-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gcodex', '0007_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInternalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Tipus d'activitat de representació",
                'verbose_name_plural': "Tipus d'activitats de representació",
                'permissions': (('manage_act_types', 'Gestionar tipus activitats internes'),),
            },
        ),
        migrations.CreateModel(
            name='ActivityAward',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itineraries.activity')),
                ('organitzation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Premi',
                'verbose_name_plural': 'Premis',
                'permissions': (('manage_act_award', 'Gestionar premis alumnat'),),
            },
            bases=('itineraries.activity',),
        ),
        migrations.CreateModel(
            name='ActivityExternal',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itineraries.activity')),
                ('organitzation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Activitat externa',
                'verbose_name_plural': 'Activitats externes',
                'permissions': (('manage_act_external', 'Gestionar activitats externes'),),
            },
            bases=('itineraries.activity',),
        ),
        migrations.CreateModel(
            name='StudentHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='itineraries.activity')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcodex.student')),
            ],
            options={
                'verbose_name': "Activitat d'alumnat",
                'verbose_name_plural': "Activitats d'alumnat",
                'permissions': (('manage_student_hours', "Gestionar hores de l'alumne"),),
            },
        ),
        migrations.CreateModel(
            name='ActivityInternalRepresent',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itineraries.activity')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itineraries.activityinternaltype')),
            ],
            options={
                'verbose_name': 'Activitat de representació',
                'verbose_name_plural': 'Activitats de representació',
                'permissions': (('manage_act_int_repr', "Gestionar activitats de representació d'alumnat"),),
            },
            bases=('itineraries.activity',),
        ),
        migrations.CreateModel(
            name='ActivityInternalColaborate',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itineraries.activity')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='gcodex.teacher')),
            ],
            options={
                'verbose_name': 'Activitat de col·laboració',
                'verbose_name_plural': 'Activitats de col·laboració',
                'permissions': (('manage_act_int_colab', 'Gestionar hores de col·laboració internes'),),
            },
            bases=('itineraries.activity',),
        ),
    ]
