# Generated by Django 4.2.16 on 2024-10-11 17:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthours',
            options={'permissions': (('manage_student_hours', "Consultar hores de l'alumnat"),), 'verbose_name': "Activitat d'alumnat", 'verbose_name_plural': "Activitats d'alumnat"},
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
