# Generated by Django 4.2.16 on 2024-10-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0009_rename_asignatura_csvdata_assignatura_and_more'),
        ('itineraries', '0002_alter_studenthours_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Data de l'anotació", verbose_name='Data')),
                ('observations', models.TextField(help_text='Anotacions en format HTML', verbose_name='Observacions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='gcodex.student')),
            ],
            options={
                'verbose_name': 'Anotació',
                'verbose_name_plural': 'Anotacions',
                'ordering': ['-date'],
            },
        ),
    ]
