# Generated by Django 4.2.16 on 2024-10-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0009_rename_asignatura_csvdata_assignatura_and_more'),
        ('itineraries', '0003_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='date',
            field=models.DateField(help_text='Data de pagament de crèdits', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='observations',
            field=models.TextField(help_text='Observacions', verbose_name='Observacions'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='gcodex.student'),
        ),
    ]
