# Generated by Django 4.2.16 on 2024-10-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0009_rename_asignatura_csvdata_assignatura_and_more'),
        ('itineraries', '0004_alter_annotations_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotations',
            new_name='Annotation',
        ),
    ]
