# Generated by Django 4.2.16 on 2024-10-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_rename_annotations_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='date',
            field=models.DateField(blank=True, help_text='Data del pagament dels crèdits (pot ser nul·la)', null=True, verbose_name='Data pagament crèdits'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='observations',
            field=models.TextField(blank=True, help_text='Observacions', null=True, verbose_name='Observacions'),
        ),
    ]
