# Generated by Django 4.2.16 on 2024-10-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_alter_annotation_date_alter_annotation_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='total_hours',
            field=models.FloatField(default=0, verbose_name="Total d'hores"),
        ),
    ]
