# Generated by Django 4.2.16 on 2024-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_annotation_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='total_hours',
            field=models.IntegerField(default=0, verbose_name="Total d'hores"),
        ),
    ]
