# Generated by Django 4.2.16 on 2024-10-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_alter_annotation_total_hours'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studenthours',
            index=models.Index(fields=['activity'], name='itineraries_activit_a272ee_idx'),
        ),
    ]
