# Generated by Django 4.2.16 on 2024-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('pla_d_estudis', models.CharField(blank=True, max_length=255, null=True)),
                ('curs_escolar', models.CharField(blank=True, max_length=50, null=True)),
                ('caracter', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estudis', models.CharField(blank=True, max_length=255, null=True)),
                ('especialitat', models.CharField(blank=True, max_length=255, null=True)),
                ('curs', models.CharField(blank=True, max_length=50, null=True)),
                ('periode', models.CharField(blank=True, max_length=50, null=True)),
                ('asignatura', models.CharField(blank=True, max_length=255, null=True)),
                ('iteracio', models.CharField(blank=True, max_length=50, null=True)),
                ('reconeixements', models.CharField(blank=True, max_length=255, null=True)),
                ('grup', models.CharField(blank=True, max_length=255, null=True)),
                ('professors', models.CharField(blank=True, max_length=255, null=True)),
                ('dni_profesores', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_corporativo_profesores', models.EmailField(blank=True, max_length=254, null=True)),
                ('expedient', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_parcial', models.BooleanField(blank=True, default=False, null=True)),
                ('estat_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('tipus_document', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_alumne', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_cognom', models.CharField(blank=True, max_length=100, null=True)),
                ('segon_cognom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('mobil', models.CharField(blank=True, max_length=15, null=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_naixement', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_iso_pais_1', models.CharField(blank=True, max_length=10, null=True)),
                ('ciutat_naixement', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_ine_ciutat', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_ine_provincia', models.CharField(blank=True, max_length=10, null=True)),
                ('comunitat_autonoma', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_ine_comunitat', models.CharField(blank=True, max_length=10, null=True)),
                ('codi_postal_naixement', models.CharField(blank=True, max_length=10, null=True)),
                ('nacionalitat', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_iso_pais_2', models.CharField(blank=True, max_length=10, null=True)),
                ('ciutat_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_ine_ciutat_residencia', models.CharField(blank=True, max_length=10, null=True)),
                ('adreca', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_deseado', models.CharField(blank=True, max_length=255, null=True)),
                ('proces_ingres', models.CharField(blank=True, max_length=255, null=True)),
                ('subproces_admissio', models.CharField(blank=True, max_length=255, null=True)),
                ('situacions_alumne', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
