# Generated by Django 4.2.16 on 2024-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
