# Generated by Django 4.2.16 on 2024-10-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0003_courseyear_expedient_student_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='asignatura',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='caracter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='especialitat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='iteracio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='pla_estudis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='reconeixements',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='total_credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
