# Generated by Django 4.2.16 on 2024-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0004_matricula_asignatura_matricula_caracter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
