# Generated by Django 4.2.16 on 2024-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0005_student_completed_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='completed_name',
            new_name='complete_name',
        ),
    ]
