# Generated by Django 4.2.16 on 2024-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0006_rename_completed_name_student_complete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('school_email', models.EmailField(max_length=100, null=True)),
                ('complete_name', models.CharField(max_length=200, null=True)),
                ('course_years', models.ManyToManyField(to='gcodex.courseyear')),
            ],
        ),
    ]
