# Generated by Django 4.2.16 on 2024-10-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0007_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['complete_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['complete_name']},
        ),
    ]
