# Generated by Django 4.2.16 on 2024-10-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0008_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='asignatura',
            new_name='assignatura',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='asignatura',
            new_name='assignatura',
        ),
    ]
