# Generated by Django 4.2.16 on 2024-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0009_rename_asignatura_csvdata_assignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='dni_alumne',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='dni_profesores',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
