# Generated by Django 4.2.16 on 2024-10-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0010_alter_csvdata_dni_alumne_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
