# Generated by Django 4.2.16 on 2024-10-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodex', '0011_delete_csvdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['complete_name'], 'permissions': (('import_codex_info', 'Importar dades del Codex'),)},
        ),
    ]
